<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <TargetFrameworkRootPath>$(MSBuildThisFileDirectory)packages\Microsoft.NETFramework.ReferenceAssemblies.net48.1.0.3\build\</TargetFrameworkRootPath>
    <PlatformTarget>x86</PlatformTarget>
    
    <!-- Terraria Path Detection -->
    <TerrariaPath Condition="'$(TerrariaPath)' == '' and '$(TERRARIA_PATH)' != '' and Exists('$(TERRARIA_PATH)\Terraria.exe')">$(TERRARIA_PATH)</TerrariaPath>
    <TerrariaPath Condition="'$(TerrariaPath)' == '' and Exists('D:\Jogos\Steam\steamapps\common\Terraria\Terraria.exe')">D:\Jogos\Steam\steamapps\common\Terraria</TerrariaPath>
    <TerrariaPath Condition="'$(TerrariaPath)' == '' and Exists('C:\Program Files (x86)\Steam\steamapps\common\Terraria\Terraria.exe')">C:\Program Files (x86)\Steam\steamapps\common\Terraria</TerrariaPath>
    <TerrariaPath Condition="'$(TerrariaPath)' == '' and Exists('C:\Program Files\Steam\steamapps\common\Terraria\Terraria.exe')">C:\Program Files\Steam\steamapps\common\Terraria</TerrariaPath>
    <TerrariaPath Condition="'$(TerrariaPath)' == '' and Exists('C:\GOG Games\Terraria\Terraria.exe')">C:\GOG Games\Terraria</TerrariaPath>
    <TerrariaPath Condition="'$(TerrariaPath)' == '' and Exists('D:\GOG Games\Terraria\Terraria.exe')">D:\GOG Games\Terraria</TerrariaPath>
    <TerrariaPath Condition="'$(TerrariaPath)' == '' and Exists('E:\Steam\steamapps\common\Terraria\Terraria.exe')">E:\Steam\steamapps\common\Terraria</TerrariaPath>
    <TerrariaPath Condition="'$(TerrariaPath)' == '' and Exists('E:\Jogos\Steam\steamapps\common\Terraria\Terraria.exe')">E:\Jogos\Steam\steamapps\common\Terraria</TerrariaPath>
    <TerrariaPath Condition="'$(TerrariaPath)' == ''">D:\Jogos\Steam\steamapps\common\Terraria</TerrariaPath>
  </PropertyGroup>
</Project>
